# Generated by Django 3.1.7 on 2022-07-19 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_auto_20220709_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='updated',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
